package com.practice.basics;

import java.util.Arrays;

enum Card {
    HEART, CLUB, SPADE, DIAMOND;

    public boolean isRed(){
        return switch(this){
            case HEART, DIAMOND -> true;
            default -> false;
        };
    }
}


public class EnumSyntax1 {

    public static void main(String[] args) {
        Arrays.stream(Card.values()).dropWhile(c->c.isRed());

        switch(Card.valueOf("HEART")){
            case HEART -> System.out.println("heart");
            case CLUB -> System.out.println("club");
            case SPADE -> System.out.println("spade");
            case DIAMOND -> System.out.println("diamond");
            default -> System.out.println("unknown");
        }
        // heart
    }
}

//1. The stream generated using Arrays.stream(Card.values()) is independent of the values present in the Card enum.
// No matter what you do to this stream, the Card enum will not be changed/affected.
//2. The stream generated by invoking dropWhile is also independent of the original stream.
// Thus, even if the resulting stream does not have HEART (or DIAMOND) in it, the original stream still has it.
//3. The switch statement in the given code is completely independent of the streams that being created in the first statement.
// Card.valueOf("HEART") will return Card.HEART (because every enum has a valueOf method that converts a String value to its corresponding enum value).
//
//Thus, the given code will print heart.